### PR TITLE
Cleaned up defs, added typing to Sources, added test file and docs, cleaned up Readme.

### PR DESCRIPTION
**Pull request by Shearerbeard**
…e, type generics now pass to sources, exported ghost module with other helpful interfaces. Test file required for definitely-typed repo included in typings directory, basic docs and usage added

### CODE REVIEW

**Comment by Shearerbeard** [comment]
Using the definition tester for the Definitely-Typed repo and implementing alt in our own app I found a some room for improvement as well as the requirement for a small test file. Updated these changes and added a page to docs to give some basic usage instruction for running alt from Typescript. Feel free to change or have me change anything if I'm not following the right conventions for documentation.

**Comment by jdlehman** [comment]
This is great! (makes me want to give typescript a spin just to try it out)

**Comment by Shearerbeard** [comment]
Thanks I'll make sure and add some of the new stuff you guys are working on when the time comes. Is extends store planned for the next release?

**Comment by goatslacker** [comment]
Nope, don't hold your breath :)

**Comment by goatslacker** [comment]
Sorry it took so long to merge, thanks for this :+1:

**Pull request merged**
