### PR TITLE
Add batchingFunction support for Flux Dispatcher

### PR DESCRIPTION
**Pull request by chrishoage**
Adds support for a batchingFunction though optional config. To be used with React.addons.batchedUpdates

Still needs tests.

### CODE REVIEW

**Comment by jdlehman** [comment]
Interesting idea, would be great to see an example of how you might use this.

**Comment by goatslacker** [comment]
We were discussing this in the gitter channel, this is the gist of it:


1. A button in ComponentA calls an action creator
2. The action creator calls an async API
3. As a result of the async call, the action creator dispatches an action
4. That action sets new state in a store
5. The new store data causes a new child to be mounted inside ComponentA
   (let's call it ComponentB)
6. ComponentB fires an action immediately, via componentDid/WillMount

this usually causes a "cannot dispatch while dispatching" error because its being taken out of context from react's batching strategy

**Comment by jdlehman** [comment]
:+1: thanks for the explanation.

**Comment by chrishoage** [comment]
Thanks for finishing this up @goatslacker! Life and work got in the way over the weekend and couldn't find time to work on it.

**Comment by goatslacker** [comment]
:+1: I'll put out a release today.

**Pull request merged**
