### PR TITLE
Improve consistency of action import on example

### PR DESCRIPTION
**Pull request by firstdoit**
From line 171 onwards, all Stores and Actions classes start with uppercase and all **created** actions and stores start with lowercase:

```
var locationActions = alt.createActions(LocationActions)
```

Therefore, in the first and foremost example, when we `export default alt.createActions(TodoActions);`, we should probably import it into a lowercase var.

Opinions on this?

### CODE REVIEW

**Comment by goatslacker** [comment]
I usually import them as uppercase because they are singleton objects, the examples at the bottom show them in lowercase because the uppercase name is already taken. So those classes should either change name or we should be consistent about this.

I don't really have an opinion though. The flux community seems to use PascalCase for stores and actions so I'm just following convention there.

**Comment by firstdoit** [comment]
You have very good points. But I can't think of a better name for the classes that won't seem artificial.

**Comment by goatslacker** [comment]
Yeah I'm not sure either other than anonymously creating the classes like:

```js
const LocationStore = alt.createStore(class {
  static displayName = 'LocationStore'

  constructor() {
  }

  ...
})
```

**Comment by jdlehman** [comment]
You could go `LocationStoreClass` though that is pretty terrible... :disappointed:

**Comment by firstdoit** [comment]
> There are only two hard things in Computer Science: cache invalidation and naming things.
> Phil Karlton

**Comment by goatslacker** [comment]
I'll be going through a docs pass in 0.17.0 and will be revising this.

**Pull request closed without merging**
