### PR TITLE
Update connectToStores ref in docs

### PR DESCRIPTION
**Pull request by frederickfogerty**
I expect a lot of issues merging this

### CODE REVIEW

**Comment by goatslacker** [comment]
Why the blob rather than the github view? The github view is there because it offers syntax highlighting for viewing and reading the source, you can always click raw to get the blob.

**Comment by frederickfogerty** [comment]
Oh, I just copied and pasted from the url, didn't know there was a difference

**Comment by goatslacker** [comment]
Oops, never mind my mistake!

**Comment by goatslacker** [comment]
Thanks :D

**Pull request merged**
