### PR TITLE
Make the IFs less verbose on BindActions

### PR DESCRIPTION
**Pull request by af7**
Not important change, just less lines (and maybe slightly more performant?)

### CODE REVIEW

**Comment by taion** [comment]
That function still reads a bit funny. Wouldn't it be better off as e.g.:

```js
      const matchFirstCharacter = /./
      const assumedEventHandler = action.replace(matchFirstCharacter, (x) => {
        return `on${x[0].toUpperCase()}`
      })

      if (this[action] && this[assumedEventHandler]) {
        // If you have both action and onAction
        throw new ReferenceError(
          `You have multiple action handlers bound to an action: ` +
          `${action} and ${assumedEventHandler}`
        )
      }
      
      const handler = this[action] || this[assumedEventHandler]
      if (handler) {
        this.bindAction(symbol, handler)
      }
```

**Comment by goatslacker** [comment]
:+1: to @taion's change

**Comment by af7** [comment]
@taion Indeed, even better, I will update the PR with your suggestion later on the day

**Comment by af7** [comment]
Ok, just updated.

**Pull request merged**
