### PR TITLE
Remove EventEmitter3 and Symbol from Alt for a smaller build

### PR DESCRIPTION
**Pull request by goatslacker**
With this change we're now at 19kb min and 5kb gzip.

### CODE REVIEW

**Comment by jdlehman** [comment]
Wow :clap:, this is heroic.

1. I can't believe transmitter was not taken on npm.
2. can you push transmitter to github so it is easier to take a look at (I am sure you probably want to get it into a more presentable state with docs/readme before you do so)

**Comment by goatslacker** [comment]
Sounds good

**Comment by goatslacker** [comment]
I have to detail exactly what this breaks. It's not much actually but I still want to have a comprehensive list.

**Comment by troutowicz** [comment]
For stores just passing a model to the  `createStore` method, it looks like testing would be a breeze!

```js
cont UnwrappedStore = AppStore.state;
```

**Comment by goatslacker** [comment]
you already have unwrapped store:

`const UnwrappedStore = AppStore.StoreModel` :)

but yes you now have access to state...

**Comment by goatslacker** [comment]
https://github.com/goatslacker/transmitter

**Comment by jdlehman** [comment]
I like the simplicity of transmitter.  This has my approval

**Comment by goatslacker** [comment]
This is merged into #253

**Pull request closed without merging**
