### PR TITLE
Fun with more decorators

### PR DESCRIPTION
**Pull request by goatslacker**
Adds support for some fancy decorators with alt

### CODE REVIEW

**Comment by jdlehman** [comment]
Really liking all these decorators. I am going to have to give in and use Babel in stage 0

**Comment by af7** [comment]
Just don't make it required please... thanks!

**Comment by goatslacker** [comment]
@af7 it's all optional of course :)

**Comment by goatslacker** [comment]
Ok let me add tests to this and docs and I'll merge.

**Pull request merged**
