### PR TITLE
Removed terse link

### LINKED ISSUE #154: Terse link on homepage doesn't go anywhere
`#no-boilerplate` does not exist in the README anymore

### PR DESCRIPTION
**Pull request by frederickfogerty**
It doesn't go anywhere!
Closes #154

### CODE REVIEW

**Comment by srph** [comment]
Might be [#flux-minus-the-boilerplate](https://github.com/goatslacker/alt#flux-minus-the-boilerplate) now.

**Comment by frederickfogerty** [comment]
Will update PR

**Comment by srph** [comment]
Might be better to create another PR since it's the in the [contribution guidelines](https://github.com/goatslacker/alt/blob/master/CONTRIBUTING.md) to keep the commit history clean.

**Comment by goatslacker** [comment]
Can you rebase this down to a single commit?

**Comment by frederickfogerty** [comment]
@goatslacker done

**Comment by goatslacker** [comment]
Thanks!

**Pull request merged**
