### PR TITLE
[fix]: issue with alt-devtool when in iframe

### PR DESCRIPTION
**Pull request by fuzzlemuttons**
Fix for an issue with alt-devtool extension when the Alt.debug function is called from an iframe, added win argument to allow for the root window to be passed in.

### CODE REVIEW

**Comment by goatslacker** [comment]
Can you please rebase all these commits

**Comment by fuzzlemuttons** [comment]
Im sorry, im not as fluent with git as i'd like, i did what i could. and it seems that there is no problems to merge these changes, is there something specific you want me to do?

**Comment by goatslacker** [comment]
`git rebase 4c3cf1109b615237b16126d07a1a8fa095ab0041~1`
fixup all your changes
`git push -f origin master`

**Comment by goatslacker** [comment]
I can cherry pick this change if anything.

**Comment by fuzzlemuttons** [comment]
I ran the commands and everything is up to date.
all those commits are part of the same change I was editing in the browser and the travis CI was returning with code style errors

**Comment by goatslacker** [comment]
Commit here 2ceeb3aeb6dd919264bcb953325bc335acce64ac

**Pull request closed without merging**
