### PR TITLE
Added a new link to an article about Altjs and React

### PR DESCRIPTION
**Pull request by richard-lopes**

### CODE REVIEW

**Comment by jdlehman** [comment]
Great find! I wonder if we should have this in a separate section called `Articles` or `Tutorials` or something since it provides more context/guidance than a typical github repo.

Maybe it is fine here for now and we can move it later if we get more articles (if that ever happens).

**Comment by rlopes** [comment]
+1

**Comment by goatslacker** [comment]
Thanks, great article.

**Comment by richard-lopes** [comment]
Thanks ! We plan to write new content around Alt.js including testing.

**Pull request merged**
