### PR TITLE
Add action testing documentation

### PR DESCRIPTION
**Pull request by jdlehman**

### CODE REVIEW

**Comment by jdlehman** [comment]
Don't merge this yet, I am going to simplify this example later today to make it easier to understand.

Also, I think the last thing we can do is add some tests to the example alt apps and reference them in the testing docs. That way people can see a real example instead of something contrived.

**Comment by jdlehman** [comment]
Ready for feedback, I updated the example so it is less confusing and more direct to the point. (no made up libraries doing magic!)

**Comment by troutowicz** [comment]
@jdlehman in case you didn't know, coverage is at 100%

**Comment by jdlehman** [comment]
@troutowicz I think another 20 notifications and I will really get it.

**Comment by goatslacker** [comment]
good job summoning it again

**Comment by goatslacker** [comment]
This looks nice. Let me load it up and give it a spin.

**Comment by goatslacker** [comment]
Looks great :+1:

**Pull request merged**
