### PR TITLE
Remove utils from alt repo

### PR DESCRIPTION
**Pull request by goatslacker**

### CODE REVIEW

**Comment by goatslacker** [comment]
If you'd like to use alt utils then: https://github.com/altjs/utils

**Comment by taion** [comment]
Can these be dropped now? https://github.com/goatslacker/alt/blob/5546e3fca6c75bd76a46b76fdc508d57a4668d9b/dist.config.js#L20-L23

What about https://github.com/goatslacker/alt/blob/5546e3fca6c75bd76a46b76fdc508d57a4668d9b/src/addons.js?

**Comment by goatslacker** [comment]
Oh yeah totally

**Comment by Bogdaan** [comment]
docs is outdated, examples not works (very bad for beginners like me)

**Comment by goatslacker** [comment]
@Bogdaan where are the examples and docs that have not been updated?

**Comment by Bogdaan** [comment]
@goatslacker 
* https://github.com/goatslacker/alt/blob/master/README.md
* http://alt.js.org/guide/container-components/
* http://alt.js.org/docs/utils/immutable/
* http://alt.js.org/docs/altInstances/

Or alt.js.org guides is not a part of this project/docs?

**Pull request merged**
