### PR TITLE
Fixed passed value to setState

### PR DESCRIPTION
**Pull request by srph**
is this right? haha

### CODE REVIEW

**Comment by mull** [comment]
This fix is indeed correct. :+1:

**Comment by goatslacker** [comment]
It's not setIn like it is now?

**Comment by mull** [comment]
Not sure I get the question @goatslacker but that is definitely how you would work with an Immutable.Map. The previous code replaced the state entirely rather than setting `todos`.

**Comment by goatslacker** [comment]
This is a change set on an old branch. Needs a rebase. Is the current one incorrect?

**Comment by mull** [comment]
Sorry, you're right. This is no longer an issue.

**Pull request closed without merging**
