### PR TITLE
add connectToImmutableStores.js

### PR DESCRIPTION
**Pull request by loopmode**
even more es7 decorator magic :) allows to easily connect to immutable stores

### CODE REVIEW

**Comment by srph** [comment]
Hmm.. isn't this already possible with the `deserialization` hook?

**Comment by jdlehman** [comment]
Yep, this is definitely possible already. @loopmode's util just does some of the boilerplate for you. though depending on if the user has custom deserialization/serialization logic, they might still have to go with the normal `connectToStores` util.

I am not completely opposed to adding this in, but my concern is if we add lots of "specific case" utils then we just bloat alt and make it harder for people to find what they need to do in the docs.  If we make utils a bit more general but configurable, then we can reduce the amount of code to maintain and make it easier to find the tool to do the job.

So after saying all that I would lean towards no on specific utils.

Curious to hear other thoughts though.

**Comment by goatslacker** [comment]
This is a good utility however I don't think I want to be stuck maintaining it. I think its time to move utils/addons outside of alt so these can just exist in user land.

**Comment by jdlehman** [comment]
:+1: to moving them outside of alt.  It looks like that is what redux is doing as well

**Pull request closed without merging**
