### PR TITLE
removed flux npm module from chat example package.json

### PR DESCRIPTION
**Pull request by jbhatab**

### CODE REVIEW

**Comment by goatslacker** [comment]
Can you add `alt` also? 

`"alt": "^0.13.5"`

**Comment by jbhatab** [comment]
well isn't it self referencing? it references the repo for alt. Do you want me to change the require call to alt too?

**Comment by goatslacker** [comment]
No because examples don't get checked-in to npm.

On changing the requires, sure.

Here's the npm package for this: https://www.npmjs.com/package/alt-chat

**Comment by goatslacker** [comment]
Thanks!

**Pull request merged**
