### PR TITLE
Remove this.dispatch from actions

### LINKED ISSUE #502: README: shouldn't updateTodo be called addTodo?
Seems like this is just adding the todo to the list.  It doesn't actually update anything, right?

```js
class TodoStore {
  ...
  updateTodo(todo) {
    this.setState({ todos: this.state.todos.concat(todo) });
  }
}
```

Or am I missing something important about how alt works?

### PR DESCRIPTION
**Pull request by goatslacker**
This is a large breaking change, fortunately a codemod is included here to automatically transform your code into the working future. 

This change has the benefit of making Action classes actual classes where you can store things on `this` or call other actions using `this.action()` rather than having that weird `actions` object.

Fixes #502 and #359 

The only caveat from #359 is that you don't get actions that don't dispatch and instead transform some data or whatever. This isn't a deal breaker for me (you can always define an outer function to transform data) but not sure how everyone else feels.

Alternatively this allows us to introduce syntax such as `this.preventDispatch()` along with `extends Actions` which will allow you to have methods in an action class that don't dispatch.

### CODE REVIEW

**Comment by taion** [comment]
I don't think this actually fixes #501. If I try

```js
class Actions {
  constructor() {
    this.foo = 2;
  }
  one() {
    return 1
  }
  two() {
    console.log('foo', this.foo)
    return 2
  }
}
```

in `foo.js`, calling `actions.two()` logs `foo undefined`.

More broadly I think this example actually pushes against having action classes at all. In the above case, I don't see the benefit of using an ES6 class there rather than just doing (assuming it worked)

```js
actions = {
  foo: 2,
  one() {
    return 1
  },
  two() {
    console.log('foo', this.foo)
    return 2
  }
}
```

**Comment by mehcode** [comment]
```
actions = {
  foo: 2,
  one() {
    return 1
  },
  two() {
    console.log('foo', this.foo)
    return 2
  }
}
```

---

```
  },
  two() {
```

It's the `,`. It's always been the `,`.

**Comment by taion** [comment]
ಠ_ಠ

**Comment by goatslacker** [comment]
Aside from the `,` having a class lets you call things on `this`. Let me check this out because that should work fine since the tests are passing.

**Comment by taion** [comment]
@goatslacker Wouldn't it be best if it were possible to call things on `this` for both class objects and POJSOs?

**Comment by taion** [comment]
On second thought, at least when using instances rather than singletons, it seems like it'd just make more sense to use classes rather than POJSOs for actions, maybe.

**Comment by goatslacker** [comment]
Ok fixed.

**Comment by taion** [comment]
Cool - so this means that for both classes and POJSOs, non-functions will show up as-is, while functions will all get turned into actions that dispatch their return values (unless they return a promise)?

One other edge case - what's the right behavior if the actions class extends another class?

**Comment by goatslacker** [comment]
instance properties work, actions don't currently.

**Comment by taion** [comment]
Looks great to me BTW.

**Comment by goatslacker** [comment]
Let me rebase and make sure that I don't need to do anything else before I land this.

**Comment by goatslacker** [comment]
Also, prior to releasing 0.18.0 I wonder if I should also figure out any other breaking changes to bundle with this one, or make upgrading more digestible by introducing only this breaking change.

**Comment by taion** [comment]
People on long enough upgrade cycles are going to end up having to do multiple upgrades at once anyway... I've had people bugging me about 5 month old installs of React-Bootstrap and trying to upgrade to React v0.14 without upgrading R-B.

Is there anything big in the pipeline? I guess maybe the server-side data fetching stuff?

**Comment by goatslacker** [comment]
Nah I'm abandoning that, leaving it up to userland.

**Comment by taion** [comment]
Huh I feel like that needs a bit of integration at the container level to work well... but I guess those containers can be in userland too.

I don't have any opinion on the stores thing.

**Comment by ziflex** [comment]
I would add my 2 cents - what if Alt have DI?
Now we can easily get any store and action from alt instance using 'getActions' and 'getStore', but what if we could register any custom services and call 'getService' for it ?

**Pull request merged**
