### PR TITLE
Add linting to travis config

### PR DESCRIPTION
**Pull request by jdlehman**

### CODE REVIEW

**Comment by jdlehman** [comment]
I will merge this in once https://travis-ci.org/goatslacker/alt/builds/54944601 fails from linting errors.

**Comment by jdlehman** [comment]
Will merge once https://travis-ci.org/goatslacker/alt/builds/54947840 fails due to linting errors.

**Comment by goatslacker** [comment]
:+1:

**Comment by troutowicz** [comment]
You're on fire @jdlehman

**Comment by jdlehman** [comment]
:fire: :fire: :fire_engine:  :droplet:

**Pull request merged**
