### PR TITLE
Added util to generate async actions

### LINKED ISSUE #285: Util for generating the 3 action pairs.
Would like a util that takes in a name and generates the 3 actions that you normally use with data sources/async:

Loading, Success, Failure actions.

### PR DESCRIPTION
**Pull request by kristenmills**
Fixes #285

### CODE REVIEW

**Comment by goatslacker** [comment]
Nice, can you add this to utils instead of core?

**Comment by taion** [comment]
Nice. `Starting` might be preferable to `Loading` for e.g. writes to remotes, though.

**Comment by kristenmills** [comment]
Yeah I can make both of those changes.

**Comment by mattkahl** [comment]
I generally like to add a `fooCompleted` as well that's triggered regardless of success or failure. I find it can be especially useful for dependent stores.

**Comment by kagux** [comment]
:+1: for `fooCompleted`/`fooFinished` as we used these a lot.
Is there anything in a way of merging this PR?

**Pull request closed without merging**
