### PR TITLE
Edit store testing docs

### PR DESCRIPTION
**Pull request by jdlehman**
- Remove example that relies too much on Alt's inner-workings
- Clean up some wording

### CODE REVIEW

**Comment by troutowicz** [comment]
:'(

I still don't like the idea of having to do a separate export solely for the ability to test. But the majority rules.

**Comment by jdlehman** [comment]
Maybe we can build out some test utils to make this easier?

**Comment by troutowicz** [comment]
What about if I alter my approach to find the symbol by string literal instead of index.

```javascript
const STATE_CONTAINER = Symbol('the state container')
```

Find the property that contains 'the state container'

**Comment by goatslacker** [comment]
That's clever but the string literal can also change in the future :)

**Comment by troutowicz** [comment]
Ah, I couldn't think of a reason why that would ever need to change. Merge away :)

**Comment by goatslacker** [comment]
It probably wouldn't, but if it does change I wouldn't classify it as a breaking change.

**Pull request merged**
